### ISSUE TITLE
amp_veltrack

### ISSUE THREAD

**Issue by paulfd** [sfzformat/sfzformat.github.io#1]
Hi!

First of all thank you so much for this wealth of information. I'm implementing sfz support and it's helping me tremendously.

I think there are small mistakes (maybe) in the amp_veltrack page. The default value should probably be 100%, right? Also, the formula would technically be 20 log (Velocity^2/127^2), since otherwise lower velocity would reach amplitude gains of 100+ decibels. For the sake of clarity, the log is probably log10 too.

Note that if the formula is correct and you have your velocity as a floating point between 0 and 1, this default curve can be slightly simplified as 40 log10( floatVelocity ).

Thanks again!! :)

**Comment by paulfd** [comment]
By the way, I assume in my implementation that it actually is the value in dB that gets multiplied by amp_keytrack, so that we have : 

gain (in dB) = 40 log10( floatVelocity ) * amp_keytrack if amp_keytrack > 0
gain (in dB) = 40 log10( 1 - floatVelocity ) * (-amp_keytrack) if amp_keytrack < 0

Does this appear correct to you?

**Comment by plgDavid** [comment]
Default value is indeed amp_veltrack=100
The 40log10 is also GM2 way (and the official SFZ way).

**Comment by redtide** [comment]
I'm not much in the technical details and in the content in general so, if fixing the default value solves the issue I would close it, is it OK?
I'm going to check and fix all SFZ1 opcode pages ATM so I will do it for all at once soon.

**Comment by paulfd** [comment]
OK for me!
________________________________

**Comment by redtide** [comment]
The default value was fixed in  2aa2010, the formula turns out to be a math equivalence so we'll leave the one in [the original documentation](http://sfzformat.com/legacy). Thank you!

**Comment by jjceresa** [comment]
@pauld 

>gain (in dB) = 40 log10( floatVelocity ) * amp_keytrack if amp_keytrack > 0
>gain (in dB) = 40 log10( 1 - floatVelocity ) * (-amp_keytrack) if amp_keytrack < 0

The above implementation feel strange.

Does the following implementation appear correct to you ?

`velocity_gain` (in dB) = 40 log10( floatVelocity ) * amp_veltrack if amp_veltrack > 0
`velocity_gain` (in dB) = 40 log10( 1 - floatVelocity ) * (-amp_veltrack) if amp_veltrack < 0

Another question. Please, does this `velocity_gain` (in dB) should be additive to `volume` opcode value (in dB) ?

Many thanks for you help.

**Comment by redtide** [comment]
@jjceresa small typo (missing "f") mentioned the wrong person. @paulfd

**Comment by jlearman** [comment]
I think it's granted that there are a number of different gains, and they all add up.  For example, there's gain due to CC7 (volume) and often CC11 (expression), in addition to gain for velocity and gain for "volume."  When I read "velociy_gain" I wondered what the units mean because I read it as "velocity increase"ather than "gain due to velocity."  I don't think we need to chante `gain` in the description.  However, it would be helpful to mention that this gain is added to  `volume` and all other gains.

The reasin the term "gain" is appropriate here is that it imlies a change in output level, rather than specifying an output level.  The term is used that way pretty consistently across audio topics in the literature.  That's just my $0.02.  If others feel adding `velocity_` makes it clearer I won't object again.

**Comment by jlearman** [comment]
Oops, I missed changing `keytrack` to `veltrack`.  If the topic is `veltrack` that's what it should be.  Is there even an `amp_keytrack`?

**Comment by jjceresa** [comment]
@jlearman

>I think it's granted that there are a number of different gains, and they all add up...However, it would be helpful to mention that this gain is added to volume and all other gains.

Thanks for this useful confirmation and clarification.

>I don't think we need to change gain in the description.

I don't think too. No need to change the wording. I wroten `gain_velocity` term only to get clarification about how velocity
is working.

>Oops, I missed changing keytrack to veltrack. If the topic is veltrack that's what it should be. Is there even an amp_keytrack?

Yes, there is an `amp_keytrack`, that produce a gain that should be additive to volume. Like this:
gain(dB) = (MIDI_key_note - `amp_keycenter`) x `amp_keytrack`

This help to add a volume change adjustment from low MIDI key to high MIDI key.

**Comment by jjceresa** [comment]
@redtide

>@jjceresa small typo (missing "f") mentioned the wrong person. @paulfd

Thanks you and sorry for this noise.

**Comment by redtide** [comment]
No noises, I just noticed and wanted to "recover" a missing recipient 😃

**Comment by paulfd** [comment]
> @pauld
> 
> > gain (in dB) = 40 log10( floatVelocity ) * amp_keytrack if amp_keytrack > 0
> > gain (in dB) = 40 log10( 1 - floatVelocity ) * (-amp_keytrack) if amp_keytrack < 0
> 
> The above implementation feel strange.
> 
> Does the following implementation appear correct to you ?
> 
> `velocity_gain` (in dB) = 40 log10( floatVelocity ) * amp_veltrack if amp_veltrack > 0 `velocity_gain` (in dB) = 40 log10( 1 - floatVelocity ) * (-amp_veltrack) if amp_veltrack < 0
> 
> Another question. Please, does this `velocity_gain` (in dB) should be additive to `volume` opcode value (in dB) ?
> 
> Many thanks for you help.

It is `amp_veltrack` instead of `amp_keytrack` yes. This is the latest implementation I have in sfizz, however it's not in the log domain so it differs from the above formula.

```c++
float velocityCurve(const Region& region, float velocity, const MidiState& midiState, const CurveSet& curveSet) noexcept
{
    ASSERT(velocity >= 0.0f && velocity <= 1.0f);

    float gain;
    if (region.velCurve)
        gain = region.velCurve->evalNormalized(velocity);
    else
        gain = velocity * velocity;

    float veltrack = region.ampVeltrack;
    [...]
    gain = std::fabs(veltrack) * (1.0f - gain);
    gain = (veltrack < 0) ? gain : (1.0f - gain);

    return gain;
}
```

**Comment by jjceresa** [comment]
@pauld, Thanks.

**Comment by jjceresa** [comment]
>@pauld, Thanks.

Sorry for the bad copy-and-paste

@paulfd, Thanks
