### ISSUE TITLE
TAL-Sampler supported opcodes

### ISSUE THREAD

**Issue by bzeiss** [sfzformat/sfzformat.github.io#128]
Hi,

I have received the current list of supported opcodes (TAL-Sampler 4.5.4 is the current one) from Patrick from TAL-Software today. Maybe this thread can be linked on the SFZ Player page in the supported opcode section.

default_path
lovel
hivel
key
pitch_keycenter
tune
lokey
hickey
volume
sample
loop_start
loop_end
loop_mode
offset
end

**Comment by redtide** [comment]
Hello and thank you for the contribution!
After some discussions there was a decision to move players' opcode support on the wiki, so there is no much maintenance problem by letting users to edit lists there.
I created the page [here](https://github.com/sfzformat/sfzformat.github.io/wiki/Player-TAL-Sampler) and added a link to the wiki on the players page.
Let me know if some other intervention is needed.
