### ISSUE TITLE
Falcon 3.0.0 opcode support

### ISSUE THREAD

**Issue by bzeiss** [sfzformat/sfzformat.github.io#129]
key, lokey, hikey, lovel, hivel, volume, pan, bend_up, trigger(attack/release),
sample, tune, transpose, pitch_keytrack, pitch_keycenter,
loop_mode, loop_start, loop_end,
ampeg_delay, ampeg_attack, ampeg_hold, ampeg_decay, ampeg_sustain, ampeg_release,
pitcheg_delay, pitcheg_attack, pitcheg_hold, pitcheg_decay, pitcheg_sustain, pitcheg_release, pitcheg_depth,
fileg_delay, fileg_attack, fileg_hold, fileg_decay, fileg_sustain, fileg_release,
fillfo_delay, fillfo_fade, fillfo_freq,
pitchlfo_delay, pitchlfo_fade, pitchlfo_freq,
fil_type, cutoff, resonance,
locc64, hicc64,
seq_position,
polyphony,

Source: https://www.kvraudio.com/forum/viewtopic.php?p=8773088#p8773088

**Comment by bzeiss** [comment]
For the wiki :-)

**Comment by redtide** [comment]
thank you!

**Comment by redtide** [comment]
Done!
