### ISSUE TITLE
"Standard Bass" instrument broken on case-sensitive file systems

### ISSUE THREAD

**Issue by suedwestlicht** [sfzformat/sfzformat.github.io#13]
https://sfzformat.com/software/instruments/basses/

-> Standard Bass

Can't load the sfz files because caps/non-caps is messed up. Directory names and file names are misspelled in the sfz-files.

Example:
Directory "Samples/Hammer-On" but in Bass_V2/Standard_Bass_V2_KSOP/Legato.sfz it's spelled "Samples\Hammer-on"

(Backslash doesn't matter since Linuxsampler translates it to a slash)

The same with filenames:
File "e3_Hammer-On1.flac" is misspelled "e3_Hammer-on1.flac".

**Comment by redtide** [comment]
This a specific instrument issue, it's not related to our website. The instrument section is just a showcase for all SFZ instruments available on the web, we don't distribute them, just link to them, so this should be forward to Unreal Instruments people.

**Comment by redtide** [comment]
We are going to report the filename case issue to the authors of the Standard Bass instrument, meanwhile I'll add a warning about this in the instruments index page, that's all we can do for now.
