### ISSUE TITLE
Request: alphabetical index

### ISSUE THREAD

**Issue by jpcima** [sfzformat/sfzformat.github.io#15]
I wish there existed an index of opcodes in alphabetical order.
I've no idea if this would be easily doable in the webpage generator, simply asking.

I would see it as a page having a large list, possibly filtered by initial letter, or a search term.
It might have 2 or 3 columns.
- name of opcode and link
- availability : v1 / v2 / Cakewalk
- category

**Comment by redtide** [comment]
We don't have a "master list" with all opcodes in.
Opcodes are parsed in the YAML file following the sequence order they are added in, there is no sort order.
I suppose we could add this on a "All opcodes" page. I wonder why not using the current columns / same layout?

As a side note; the website is static, there is no way to customize the page, so if there would be other preferences they should be applied again in other pages. I wonder if there could be a better solution to handle this, maybe the only way would be by using javascript.
