### ISSUE TITLE
SFZv2 effects

### ISSUE THREAD

**Issue by jpcima** [sfzformat/sfzformat.github.io#21]
Hello, below is some analysis of the effects and their routing, in Cakewalk SFZv2.
The content below is free to reuse. (CreativeCommons-0)

---

**Routing graph**

There are 5 buses that I know of: Main, Fx1, Fx2, Fx3, Fx4

The `<effect>` are processed in series in the bus which they belong to. It's the order of appearance in the file.

Note there is also a `Mix` node. I don't know the exact purpose, maybe it was there for extension purposes. It sums into the `Main` output.

![Effect routing](https://user-images.githubusercontent.com/17614485/75467079-75ce4500-598b-11ea-9e26-3ec28edb57c8.png)
[Effect routing.svg.gz](https://github.com/sfzformat/sfzformat.github.io/files/4262898/Effect.routing.svg.gz)
[Effect routing.drawio.gz](https://github.com/sfzformat/sfzformat.github.io/files/4262899/Effect.routing.drawio.gz)

---

**`<region>` Opcodes**

- `effectN` (with N: 1-4, was 1-2 in SFZv1)

Gain of the region's send into the Nth effect bus. (the `bus=fxN` effects)
It's the contribution of the region to the bus's input mix.
Translates from % into a linear gain 0-1.
Unit:% Default:0%

---

**`<effect>` Opcodes**

- `type`

As in the current spec.
Only a remark: "autopan" is known as "apan" in the software.

- `bus`

Possibles are:
    - `fxN` with N: 1-4
    - `auxN`: I don't have infos on these
    - omitted, other: it goes to the Main bus (I guess, "the SFZv1 one")
      possibly the official name is "main", according to some traces in the binary, but use any unrecognized name for bus and it will route to Main regardless.

Default: main

- `directtomain`

Global, set it under any `<effect>` header for identical effect.

Gain of the Main bus into the output. (cf. routing graph)
Translates from % into a linear gain 0-1.
Unit:% Default:100%

- `fxNtomain`

Global, set it under any `<effect>` header for identical effect.

Gain of the Nth effect bus into the output. (N: 1-4, cf. routing graph)
Translates from % into a linear gain 0-1.
Unit:% Default:0%

- `fxNtomix`

Global, set it under any `<effect>` header for identical effect.

Gain of the Nth effect bus into the Mix node. (N: 1-4, cf. routing graph)
Translates from % into a linear gain 0-1.
Unit:% Default:0%

**Comment by jpcima** [comment]
Regarding bypass:

**<effect> Opcodes**

- `bypass_onccN`

Set up a bypass controller for the effect.
When the MIDI CC value (0-127) is >= a threshold, the effect plays, otherwise it's disabled.

The threshold is determined according to this expression:
`f(x) = 64.0 / BypassValue`

where BypassValue is the opcode's value, strictly positive, interpreted as real number.

At `BypassValue`=1, without doubt the most useful, it's `off` at `CC<64` and `on` at `CC>=64`

**Comment by DSmolken** [comment]
Added most of this info to the effect header, also filled in more about the differences bewteen SFZ v1 and SFZ v2 effects handing in the effect opcode pages.

Did we miss anything, and is there any info anywhere about what's really SFZ v2 and what's Cakewalk-specfic?

**Comment by jpcima** [comment]
>Did we miss anything, and is there any info anywhere about what's really SFZ v2 and what's Cakewalk-specfic?

- `bus`, `fxNtomain`, `defaulttomain`, `effectN`
These have some examples in the rgc v2 test suite, Cakewalk software all have them.

- `fxNtomix`, `bypass`
Not in the test suite and no other info, the Cakewalk software have them.

- `dsp_order`, `<effect>internal=on`, extended routing graph (FX->DSP various arrangements)
This is in Rapture only.

**Comment by DSmolken** [comment]
Added that stuff. I guess there are also settings for specific parameters for specific effects, like reverb_damp and delay_feedback. Could list those somewhere, if we can find a complete list.

**Comment by jpcima** [comment]
Sure, this takes a bit of time, but I'll try make you the best list I can.

**Comment by DSmolken** [comment]
Thanks, that's a lot of information! Added that to the type opcode page for now, will possibly move to proper opcode pages later.
