### ISSUE TITLE
Add OpenMPT to software list

### ISSUE THREAD

**Issue by sagamusix** [sfzformat/sfzformat.github.io#22]
[OpenMPT](https://openmpt.org/) can import and export SFZ files, but its engine is not based on SFZ so only a relatively small number of opcodes is supported. Would it still make sense to add it to second table at https://sfzformat.com/software/players/ maybe?

The list of supported opcodes is here: https://wiki.openmpt.org/Manual:_SFZ_Implementation

License is FOSS (3-clause BSD), native support for Windows, but also runs through Wine on macOS and Linux.

**Comment by redtide** [comment]
Why not, will do soon!

**Comment by redtide** [comment]
Added in 4c83f99.

**Comment by sagamusix** [comment]
Awesome, thanks for the quick response :)
