### ISSUE TITLE
Add `eqN_type` to SFZv2

### ISSUE THREAD

**Issue by jpcima** [sfzformat/sfzformat.github.io#24]
Hello. Cakewalk SFZ has an opcode `eqN_type` which sets the type of EQ filter.

Values are the following
- `peak` (default)
- `lshelf`
- `hshelf`

Example
```
<region>
eq1_gain=20 eq1_freq=10000 eq1_bw=1
eq1_type=lshelf
```

**Comment by DSmolken** [comment]
Interesting discovery! Do you know if Cakewalk also allows three EQ bands, or can it maybe do eqN with N>3?

**Comment by jpcima** [comment]
It's also 3 bands maximum.

**Comment by DSmolken** [comment]
Thanks, that's all the info we need to know. Will document this when time permits.

**Comment by redtide** [comment]
Added in 478f689

**Comment by redtide** [comment]
... and completed in 06daf39, closing, thanks!
