### ISSUE TITLE
Comparative table of feature support in SFZ players

### ISSUE THREAD

**Issue by mxmilkb** [sfzformat/sfzformat.github.io#3]
Would make comparisons easier and quicker.

**Comment by redtide** [comment]
From menu Software -> [Players](https://sfzformat.com/software/players) you can look for documented SFZ players (except Sforzando that uses the [ARIA](https://sfzformat.com/software/players/aria) engine, the link points to the related product page) clicking from a player name link, but we have no an "all players" comparison table. Currently I removed the LinuxSampler one, linking to [their sfz page](http://linuxsampler.org/sfz/) instead which has its own opcode support table.

**Comment by mxmilkb** [comment]
It would be even more informative to group information about what file formats each SFZ player can handle, along with the name of the related library the software.

**Comment by redtide** [comment]
BTW I'm not sure we want to maintain other people software information if they don't give it to us, this work was started as "we know about the existence of some software out there, here is a list" thing in the beginning

**Comment by mxmilkb** [comment]
"if they don't give it to us"

how is that currently the case?

**Comment by redtide** [comment]
the current case might be that IDK which audio formats are supported by sfzero or zerberus (musescore), only for sfizz and (AFAIK also) liquidsfz because libsndfile. I'm not even sure about Sforzando... (currently I'm the only one working on those lists with all the information I can get from others...)

**Comment by mxmilkb** [comment]
Have you started? Have you made any notes? Can you enable one of the sfz wikis so notes can be taken?

**Comment by redtide** [comment]
I'm sorry but I think in the end this is something that cannot be maintained except by their developers. If you are interested, the wiki is active.
