### ISSUE TITLE
Improve modulations/curvecc

### ISSUE THREAD

**Issue by jpcima** [sfzformat/sfzformat.github.io#31]
Hello. This page is very confusing. It doesn't explain at all what `curvecc` is.
I think, there should be at least a text that explains the purpose, how it works and relation with the `<curve>` header. Also an example would not be too bad.

**Comment by redtide** [comment]
Unfortunately that is an unfinished work in progress, just an old page that was moved there as partial content with the need to have a dedicated section for single modulations explained in a generic way.

**Comment by jpcima** [comment]
A proposal below for a more useful text.

```
The `curvecc` modifier, when it's present, designates a curve[1] which shapes
the controller input. If absent, the default curve is used, a straight line
which runs from 0 to 1.

The value of `curvecc` is a positive integer. It is the index of a curve,
either builtin or user-defined, which corresponds to the <curve> opcode
`curve_index`[2].

[1] link to <curve> header
[2] link to curve_index opcode
```
