### ISSUE TITLE
Incorrect modulations/stepcc

### ISSUE THREAD

**Issue by jpcima** [sfzformat/sfzformat.github.io#32]
This definition is incorrect, or at least misleading.
https://sfzformat.com/modulations/stepccN

It states:
`Sets the number of steps with which the modulation target is modulated by MIDI CC N.`

In reality, it sets the interval between consecutive steps, not the step count.
Which does indeed, affect the step count, but that's not the meaning of the value.

This formulation has led the author of sfizz into a mistake in the past, so it will be better to rewrite it without confusion.

As an example:
```
<region>
sample=*sine
pitch_oncc16=1200
pitch_stepcc16=300
```

This describes a pitch controller which has 5 positions.: 0, 300, 600, 900, 1200.

**Comment by redtide** [comment]
Thank you!
