### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jpcima** [sfzformat/sfzformat.github.io#33]
Hello, can there be a license by which the documentation is distributed?
From some distant memory, I recall some discussions about "public domain". If it is, it will be great to put the work under CC0 license. (public domain-ish)

When making an advanced editor for SFZ at a future point, it will be appreciated that the data is freely distributable, so it can be shipped as part of the software, and available as code assistance tool for SFZ writers. (listing, completion, tooltip, reference panel, and so on)

**Comment by redtide** [comment]
Applied in 6d129bc

**Comment by jpcima** [comment]
This is great, thanks ! cc @trebmuh
