### ISSUE TITLE
Document potentially confusing #define / #include interaction

### ISSUE THREAD

**Issue by sagamusix** [sfzformat/sfzformat.github.io#34]
Given the following snippet:

```
#define $foo 1
#include "some_file_that_uses_foo.sfz"
#define $foo 2
#include "some_file_that_uses_foo.sfz"
```

One would expect that the first time "some_file_that_uses_foo.sfz" is included, it uses a `$foo` value of `1`, and the second time it uses a `$foo` value of `2`.

At the very least, sforzando doesn't fulfill this expectation: It will use a value of 2 both times. Other implementations will probably follow the more straight-forward interpretation mentioned before (at least my own implementation does).

I think it would be a good idea to point this issue out in the `#define` documentation so that people don't expect either of the two behaviours to be The One And Only Correct Behaviour and then complain that their instrument doesn't work properly in another SFZ player.

**Comment by jpcima** [comment]
Is this only when includes are the same file?
What would happen in the following case:
```
#define $foo 1
#include "A.sfz"
#define $foo 2
#include "B.sfz"
```

**Comment by sagamusix** [comment]
No, it doesn't matter if it's a different file. I have a feeling that defines and includes are processed in two different passes in Sforzando, causing this issue.

**Comment by sagamusix** [comment]
Example:
```
<region>
key=60
#define $sample *saw
#include "inc1.sfz"

<region>
key=61
#define $sample *sine
#include "inc2.sfz"
```
with the content of both include files being `sample=$sample`.
