### ISSUE TITLE
Visual illustration of curves would be great.

### ISSUE THREAD

**Issue by squinkylabs** [sfzformat/sfzformat.github.io#52]
I'm having a little trouble understanding amp_velcurve_N and similar. I see there is a link to an external curve generator site, but just like with the shape of the envelopes, it would be nice to have more information on what these curves actually do and what the number mean.

**Comment by kinwie** [comment]
`amp_velcurve_N` will cause the curve to be linear from each to each velocity boundaries. That's all I know

**Comment by squinkylabs** [comment]
@kinwie : thanks. Yeah, the amp_veltrack is documented quite well, not problem there. sounds like the curves are not as will documented.

**Comment by DSmolken** [comment]
I'll see if I can improve the examples.

**Comment by DSmolken** [comment]
Better examples. Are things clear now, or should we still add pictures?

**Comment by squinkylabs** [comment]
oh, that's much better. thank you. A couple of minor points.

a) It doesn't really say (or I missed it) if the velcurve is applied before the normal decibel curve that amp_veltrack uses, or if the velcurve replaces that curve.

b) ultra pedantic: is says amp_velcurve_0 is legal, but doesn't say what it means.
```
amp_velcurve_0= 0
amp_velcurve_127=1
```
does that mean at 1 the curve would be 1/128? Or does it mean "zero is an illegal velocity, but since sfz files already use it we are going to say it's officially supported here, and amp_velcurve_0 actually should be interpreted as amp_velcurve_1"?

**Comment by DSmolken** [comment]
Added a little more about vel=1 and amp_veltrack. Not sure how the math works out, that would need to be checked by running the equations.

**Comment by squinkylabs** [comment]
very nice!
