### ISSUE TITLE
loop_crossfade

### ISSUE THREAD

**Issue by sagamusix** [sfzformat/sfzformat.github.io#54]
Currently [loop_crossfade](https://sfzformat.com/opcodes/loop_crossfade) documentation says: "It’s unknown whether this opcode is actually implemented anywhere."

This opcode is implemented in OpenMPT. I find it really useful because it allows me to leave samples completely untouched while still being able to apply proper loops that don't click.
OpenMPT's crossfade implementation currently applies a fade halfway between a constant volume fade and constant power fade (`amp = pow(x, 0.75)`) simply because I found that this is a good compromise for all sorts of sample types. For SFZ 3, it would probably make sense to add an opcode which allows the fade law to be changed.

**Comment by jpcima** [comment]
sfizz implements and uses a sinusoidal formula as default `(1.-cos(pi*x))/2.`.
+1 on ability to choose among various curves. (or using SFZ `<curve>`?)

**Comment by sagamusix** [comment]
Hmm, the predefined curves might be a bit of a limited choice, and hand-made curves are probably a bit too coarse for a good crossfade. But it might be a good additional option.

**Comment by DSmolken** [comment]
Updated what we have so far. Do we also need to update some tables about which players are supported?

**Comment by sagamusix** [comment]
Looks good to me for the time being, thanks for the update! I think the rest of the discussion should continue in sfz/opcode-suggestions.
