### ISSUE TITLE
Is there a spec for what can be in an opcode's value string?

### ISSUE THREAD

**Issue by squinkylabs** [sfzformat/sfzformat.github.io#55]
I know from experience that `sample=a b` means the filename is `a <space? b`. But what does `sample=a //b` mean? Is the filename `a`? or `a <space>`?

**Comment by jpcima** [comment]
No unfortunately there isn't. The grammar is pretty much defined by implementation.
The best thing to consider as a specification, for time being, is whatever sforzando implements.
The software out there disagree on various edge cases of SFZ parsing, but it is safely assumed that most instruments out there comply to ARIA.

Formalizing the SFZ grammar would be helpful, but the design does not make it easy.
This would probably have to be expressed using a backtracking parser model.

> But what does sample=a //b mean? Is the filename a? or a <space>?

This would be "a", the values cannot have trailing spaces.

**Comment by squinkylabs** [comment]
Oh, for sure it's much too late to try to make a "spec" that's anything but the reference player. When I first come to SFZ I was astounded there wasn't any proper language spec, but didn't take too long to figure out sforzando IS the spec. And now I am removing those training spaces ;-)

Thanks again!
