### ISSUE TITLE
it sure would be cool to document volume in one place

### ISSUE THREAD

**Issue by squinkylabs** [sfzformat/sfzformat.github.io#56]
There are so many opcodes that affect volume. all the velocity stuff, the cc fade and cross fade stuff. A dream would be to see a formula somewhere the expressed gain as a function of all the opcodes, the velocity and some cc values.... 

That said, the individual parts are documented pretty well. thanks!

**Comment by DSmolken** [comment]
So, volume, amplitude, xfin/xfout, amp_veltrack, amp_velcurve_N, ampeg, amplfo, egN_volume, lfoN_volume... anything else I'm forgetting?

**Comment by squinkylabs** [comment]
haha - you know why more than I do about this, but that looks like a very complete list to me!

**Comment by DSmolken** [comment]
I wonder what the best place to put this on the site would be... a tutorial covering "all things volume", maybe? Or is there a better/more logical type of page for this?

**Comment by redtide** [comment]
Add another type of [category list]? But I'm not sure if to add this in the YAML DB.

[category list]: https://sfzformat.com/misc/categories

**Comment by DSmolken** [comment]
Hmmm... yeah, exactly, not sure, this would be a one-off page probably as things like filter cutoff and pitch which can be modulated by multiple sources still aren't nearly as complicated as volume. Maybe I'll just make a tutorial for now, and we can then move stuff later.

**Comment by DSmolken** [comment]
https://github.com/sfzformat/sfzformat.github.io/blob/source/tutorials/volume.md is a start, hopefully covers most of it as an outline and now needs detailed info pasted in from existing pages.

**Comment by squinkylabs** [comment]
oh, that's really nice. thanks.

For me, after the explanation you are working on, I'd like to see an example or two. like "vol = x crossfade set up like xyz" then the final gain applied to the sample will be a + b * c + qrst...  I think you get the idea.

But this is already going to be a great addition to the document. thanks agian.

**Comment by redtide** [comment]
Not sure some search result lists could satisfy your request, I think it's hard to keep all of these in one place.
