### ISSUE TITLE
sw_lokey / sw_hikey specs coherency issue

### ISSUE THREAD

**Issue by jjceresa** [sfzformat/sfzformat.github.io#64]
The page describing `sw_lokey, sw_hikey` opcode (http://sfzformat.com/opcodes/sw_lokey) says "This affects sw_last keyswitches only, and sw_down keyswitches can be outside of this range..". However the page describing `sw_down` opcode
says "Enables the region to play if the key equal to sw_down value is depressed. Key has to be in the range specified by sw_lokey and sw_hikey.".
This leads to a coherency issue. Please, does anyone would give explanations ?

**Comment by DSmolken** [comment]
Will check that and correct... I probably got sw_down and sw_previous mixed up somewhere.

**Comment by jjceresa** [comment]
>Will check that and correct... 

Oh, many thanks for fast answer !

**Comment by DSmolken** [comment]
Fixed now - please take a look if it makes sense now. The sw_down page was correct, and the actual behavior is implementation-dependent. I got sw_down and sw_previous mixed up in the sw_lokey and sw_hikey pages, so those are now updated.

**Comment by jjceresa** [comment]
>Fixed now - please take a look if it makes sense now.

Yes, it makes sense. `sw_lokey, sw_hikey`, `sw_down, sw_up`, and `sw_last, sw_previous` pages are now coherent.
Please, feel free to close this issue.
Many thanks.
