### ISSUE TITLE
About loop_mode=loop_continuous behaviour

### ISSUE THREAD

**Issue by jjceresa** [sfzformat/sfzformat.github.io#70]
The `loop_mode` page says " In loop_continuous mode, the loop will repeat if the loop end is reached during the release phase."

Please, does it mean that the loop should also repeat if the sample `end` is reached ?

**Comment by DSmolken** [comment]
Hmm... If the loop end is a point before the sample end, the sample end will not be reached, as the sample will go back to the loop start before reaching the end. If the loop end is the sample end, both will be reached simultaneously. So, there's no risk that the sample will stop playing when end is reached, though we might need to test what happens if loop_mode=continuous is set for a sample which does not have any loop points defined.

**Comment by jjceresa** [comment]
>If the loop end is a point before the sample end, the sample end will not be reached, as the sample will go back to the loop start before reaching the end.

Ok.

>If the loop end is the sample end, both will be reached simultaneously. So, there's no risk that the sample will stop playing when end is reached

Ok.

1)Now, if loop_start or loop_end are outside the sample range [start, end], I guess that it is a design mistake and in this case the sfz player parser should reject the region concerned. Opinion ?

>though we might need to test what happens if loop_mode=continuous is set for a sample which does not have any loop points defined.

From the specs, if loop points are not defined then default value 0 applies for both loop_start and loop_end. Again, I guess that the sfz parser should check if these loop points are coherent with sample start, stop points (as stated in (1)) ?.

Thanks for your opinions.

**Comment by DSmolken** [comment]
Yeah, having loop_end be past end gets rejected at least by the ARIA parser. We should test what really happens when loop_end is undefined and loop_mode=continuous is specified, though, because I'm not sure.

**Comment by DSmolken** [comment]
Just tested this - no loop, and loop_continuous, ARIA will keep looping when the sample end is reached, even if the ampeg_release time is long enough for the entire sample to repeat several times after the key's been released. Should I add a clarification about that to the loop_mode opcode description?

**Comment by redtide** [comment]
under a Practical Considerations section?

**Comment by jjceresa** [comment]
>Just tested this - no `loop points`, and `loop_continuous`, ARIA will keep looping when the sample end is reached, even if the ampeg_release time is long enough for the entire sample to repeat several times after the key's been released.

That means that ARIA engine assumes that the undefined `loop_start`, `loop_end` are set with respective sample `start` and sample `end` values ignoring the default value 0 for both `loop_start` , `loop_end`. In others words loop_continuous is similar to one_shot except that this one_shot is continuously looping.

>Should I add a clarification about that to the loop_mode opcode description?

I think that it worth to clarify this.

Many thanks for testing this. And thanks also for the examples provided under the tutorials section. These are very useful.

**Comment by jjceresa** [comment]
Thanks for the clarification you added under "Practical Considerations" section.
