### ISSUE TITLE
rt_decay comment seems confusing

### ISSUE THREAD

**Issue by jjceresa** [sfzformat/sfzformat.github.io#71]
The rt_decay opcode semantic describes a volume decrease (in decibels) per seconds after the note has been attacked.
(http://sfzformat.com/opcodes/rt_decay)

In other words the more is the `duration` of the note since note on, the more the region triggered on note off should get a `volume decrease`.

However,
1) comment in the `rt_decay` says "Range is 0 to 200. In general, higher values mean `quicker` decrease, which makes sense for cases where the note sustains longer".
To be coherent "quicker" should be replaced by "high".

2)Also, "For example, higher piano notes decay much faster than lower ones, so the higher notes will need higher rt_decay values". This seems incoherent  because it relate the fast decay of high notes (which produce a short duration for high notes) with higher rt_decay.

Thanks you for any opinions.

**Comment by DSmolken** [comment]
Tried to fix that, is it OK now?

**Comment by jjceresa** [comment]
>is it OK now?

Oh yes, now the comment example is clear. I'm a beginner learning SFZ specs so many thanks for your clarification.
