### ISSUE TITLE
Recommend lossless/lossy audio formats to ensure compatibility and a good experience

### ISSUE THREAD

**Issue by kmturley** [sfzformat/sfzformat.github.io#73]
First-off I wanted to say this is amazing. I believe in open-source and the sfz format. I am planning to support it for my project: https://studiorack.github.io/studiorack-site/ However there are a few things we could improve.

**Problem**

When creating an .sfz file there are many possible audio file/formats to chose from, with varying licenses and cross-platform support. I can publish .sfz files along with wav, flac, ogg or even mp3 files. Users can download these but their platform/player has to be able to support them. If not the file does not load, or the playback is buggy/untested. This creates inconsistency and ultimately a poor user-experience.

For example, sfizz appears to support playback of wav, flac, mp3, ogg, aiff, but I had to dig into the source-code to find it out:
https://github.com/sfztools/sfizz/blob/acd866fd3d247d2fc659593cac96e88e801c29e2/external/st_audiofile/src/st_audiofile_libs.h
sforzando appears to support wav, ogg and flac. But as there is no list of formats, I have no way of knowing that my .sfz file will be supported without testing with every player...

* As a SFZ author, I would like to be recommended which lossless/lossy audio formats will ensure a good player-experience and compatibility
* As a SFZ user, I would like to download .sfz files from different authors, and not have to worry about whether my player is compatible, or playback is buggy.

**Investigation**

There seems to be two main use-cases:
1) Lossy version - Quick download to test them out, or for experimenting fun music
2) Lossless version - Producing professional music, exporting final versions of tracks.

It seems that every .sfz should be released in those two versions at a minimum, and the two formats used, should be supported by a majority of .sfz players

In the original Cakewalk documentation it states:
_"Two kinds of sample files were selected to be included in the sfz format: a basic PCM uncompressed format (standard Windows wave files) and a basic, adjustable-quality, royalty free compressed format (ogg-vorbis encoded files). The inclusion of a compressed format allows sample developers and soundware creators to easily create preview or demonstration files in a small package so they can be transferred with minimum bandwidth, while retaining complete performance functionality."_
https://sfzformat.com/legacy/

They intended two versions, using .wav and .ogg formats. Therefore all players should support these formats to comply with the original specification.

This was likely before the introduction of .flac as an improved lossless (but compressed) audio format

It appears this context has been lost in the new documentation, but would be very useful for .sfz authors. 

**Solution**

Create a page called Samples containing context on the recommend file/format types (lossless vs lossy), and link to the homepage list here:
_To make use of the SFZ format requires three things:_
_* Samples_
_* SFZ player_
_* SFZ file_
https://sfzformat.com/

Add the audio formats each player supports to this page:
https://sfzformat.com/software/players/#players

**Comment by redtide** [comment]
> Create a page called Samples containing context on the recommend file/format types (lossless vs lossy), and link to the homepage list here

Good idea.

> Add the audio formats each player supports to this page

I don't know if that's possible and I guess also a maintenance problem.

**Comment by DSmolken** [comment]
I think we can add currently supported file formats for at least ARIA and sfizz, I don't expect it to require much maintenance. If we know what formats they currently support, I don't expect that to change often.
