### ISSUE TITLE
Recommend default directory paths for .sfz files

### ISSUE THREAD

**Issue by kmturley** [sfzformat/sfzformat.github.io#74]
I'm working on a project: https://studiorack.github.io/studiorack-site/ which allows audio plugins to be installed via:

- Website (manual download of .zip files)
- App (automatically download/extract/move to plugin directories)
- Command line tool (automatically download/extract/move to plugin directories)

**Problem**

I downloaded several different sfz packs and extracted the folders to directories on my harddrive. When opening sfz players such as sfizz and sforzando, I had to manually find/navigate to the extracted files. The default directory for each player was different:

- sforzando defaults to: /Library/Application Support/Plogue
- sfizz defaults to: /Users/username/Documents/SFZ instruments

This inconsistency also means that SFZ players cannot scan the default folder and automatically detect .sfz files. Requiring manual effort by the user.

- As a SFZ author, I want to distribute an installer, which automatically downloads/extracts/moves/installs the pack into a recommended sfz default directory, saving users time and avoiding any manual mistakes
- As a SFZ user, I want to install/extract sample packs into a recommended sfz default directory, where my .sfz player will automatically detect the files and show the instrument in a dropdown.

**Investigation**

The VST specification is very specific about VST plugin and preset default locations:
https://developer.steinberg.help/display/VST/Plug-in+Locations
https://developer.steinberg.help/display/VST/Preset+Locations

This creates consistency, it allows installers to install VST plugins and presets into the correct directories. Plugin hosts know where to look first, improving the user-experience (less manual looking for folders/locations) and more efficient than scanning the entire harddrive for .vst files.

**Solution**

Add guidelines for SFZ packs:

- File/folder structure: .zip file containing .sfz .wav files etc
- Versions: lossy, lossless
- Installation directory: per platform Linux, Mac, Win

These will allow players and installers like my own to follow the guidelines are have compatibility

**Comment by redtide** [comment]
> This inconsistency also means that SFZ players cannot scan the default folder and automatically detect .sfz files.

I don't see any inconsistency, it's just a personal preference from their developers, and I don't see why people like to have a single folder where to put everything in.
sfz instruments can be really huge, so anyone can choose to fill one (or more?) dedicated disks or partitions, so if you want to assign a path for sfz in your software, you can simply create a list box where to add one or more paths to scan, if empty just return a message box to the user if someone really need to know where all the files are.
There is no consistency in forcing a single place, it's rather a limitation like in VST3 that only recently they added support for an user folder where not everyone have system admin rights. Sampled instruments are not plugins anyway.

**Comment by DSmolken** [comment]
Yeah, default file location currently isn't part of the standard. To standardize it would take asking sfz player developers to update their software. Which is fine, if they do it we can document it, but we can't make them do anything.
