### ISSUE TITLE
Please add sfizz opcode `hint_sustain_cancels_release`

### ISSUE THREAD

**Issue by jlearman** [sfzformat/sfzformat.github.io#75]
sfizz has a new opcode to make sustain operate more realistically (for pianos.)

If the sustain pedal is depressed while any notes are in the release phase, those notes go back into sustain phase.  This mimics the behavior of a real piano: if you play notes, release them all, but before they die out press the sustain pedal, any notes that were still ringing will continue.  This happens regardless of whether or not the sampleset has release samples.

The opcode is in the <control> section and affects the entire sfz file load.  The value "on" enables the feature.  By default it is off.

For more info: https://github.com/sfztools/sfizz/issues/885

**Comment by redtide** [comment]
I don't think sfzformat is the right place for that, there is instead a generic [hint_*](http://sfzformat.com/opcodes/hint_) page for referring a custom implementation of an opcode series related to ARIA. I think it should be added in the [sfztools](https://sfz.tools/sfizz/development/status/opcodes/?q=hint) site instead.
EDIT: ~~One thing that should be done is to change the page content explaining that it might be an idea adopted also by other samplers, like sfizz~~ it's already stated that "Other engines could implement other hints as they wished".

**Comment by paulfd** [comment]
Note that this is now overridden by the plugin option (when using the LV2 or VST3 plugin).

**Comment by redtide** [comment]
[Added](https://sfz.tools/sfizz/development/status/opcodes/?q=hint) to sfz.tools website.
