### ISSUE TITLE
Need some complement confirmation about sw_lokey sw_hikey, sw_last, sw_down, sw_up behaviour

### ISSUE THREAD

**Issue by jjceresa** [sfzformat/sfzformat.github.io#77]
The sfz specification clearly defines that the opcodes `sw_last, sw_down or sw_up opcode` values must be in the the range specified by `sw_lokey` and `sw_hikey`.
So the sw_lokey and sw_hikey range allows the musician to define a `key switch range` on his keyboard. 
My question is : Does this `key switch range` should behave exclusively silent when the musician depress a key in this range ?
In others word the question could be: Is there something in the sfz spec. that says that this `key switch range` must be silent or not depending on certain conditions when the musicians plays on his keyboard ?

Many thanks for any answers.

**Comment by jlearman** [comment]
Note that there may be other `region` blocks that are independent of the key switching specified using the above opcodes, so no: there should be no guarantee of silence.  The normal rules apply: if no region satisfies a given note-on event, then no region plays.

**Comment by sgossner** [comment]
The purpose of sw_lokey and sw_hikey is **strictly** to provide the sampler engine with a _range_ for checking for `sw_last`. It has no reason to be silent and indeed will not be silent if you put a sound in that range in a different region, as jlearman suggests.

I just confirmed I could add and trigger notes within the sw_lokey/sw_hikey range in the ARIA engine. This is actually useful and desired, for example, for realistically adding sounds like pulling stop levers, inserting mutes, adjusting snares, etc.

From the wiki on "sw_lokey / sw_hikey":
"... In ARIA, either `sw_down` or `sw_up` can be a note in the playable range, regardless of whether `sw_lokey/hikey` is defined or not. In rgc sfz, they can be in the playable range if `sw_lokey/hikey` are not defined, but if they are defined, then `sw_down` and `sw_up` notes must fall in the `sw_lokey/hikey` range."

**Comment by jjceresa** [comment]
Many thanks to @jlearman and @sgossner for those clarifications. Now I understand, the normal rule apply. By default all regions have lokey = 0 and hikey = 127, so,  if there are no others region blocks opcodes then the regions play in the full keyboard range (0 to 127) regardless sw_lokey/sw_hikey range. if the musician wants to get sw_lokey/sw_hikey range silent then he must explicitly exclude the sw_lokey/sw_hikey range out of of the  lokey/hikey range for all regions.

**Comment by sgossner** [comment]
@jjceresa Yes.

It is in good form: (1) to not 'stretch' acoustic (real) samples more than a minor third up or down, (2) to constrain acoustic (real) samples to the real playing range of the physical instrument, and (3) to place keyswitches (sw_lokey/sw_hikey) several notes outside the lower or upper limit of the instrument, so there is a buffer between playable range and keyswitches.

If using a synthesized sound, where you usually can map it out across most of the keyboard just fine, or an acoustic instrument where the range is excessive to the point that keyswitches are not ergonomic (like organ or piano), then perhaps consider an alternative mode to changing the articulation/sound, such as continuous controllers (loccN/hiccN, whereas N = CC number desired).

**Comment by jjceresa** [comment]
@sgossner, those advice are useful, thanks again.
