### ISSUE TITLE
discord invite link expired

### ISSUE THREAD

**Issue by jeffythedragonslayer** [sfzformat/sfzformat.github.io#79]
Hi, I am trying to follow the invite link on https://sfzformat.com/ to join the discord but it's expired.

**Comment by DSmolken** [comment]
Discord was having general login issues at that time so that might have caused it. Can you try again? If it still doesn't work then the easiest thing for us to do might be to just generate a new invite link and update the page, but hopefully it'll work now.

**Comment by jeffythedragonslayer** [comment]
I can't send anyone any messages on discord at all anymore; it says "API Outage"

**Comment by DSmolken** [comment]
Seems like the general Discord issue, then, not specific to our server. I can now get into Discord, but it seems they're still not up to 100% user capacity. I got no better ideas than "try again in a few hours or tomorrow, it should work then".

**Comment by jeffythedragonslayer** [comment]
Ok, I'll try again soon.  Discord had told me that specific link had
expired.  If that's not true and it's a general discord problem instead
then it shouldn't be saying that about links.

**Comment by jeffythedragonslayer** [comment]
I'm in the discord now.
